[book]
authors = ["kuanhsiaokuo"]
description = "主要介绍基于macOS/iOS平台的工作/学习/效率工具及相关工作流，包含但不限于开发/设计/管理/研究型工作"
language = "cn"
multilingual = false
src = "src"
title = "Apple Power User  "

[output.html]
theme = "mytheme"
default-theme = "rust"
git-repository-url = "https://github.com/KuanHsiaoKuo/osx_basic_configuration.git"
git-repository-icon = "fa-apple-core"
additional-js = ["assets/mermaid/mermaid.min.js", "assets/mermaid/mermaid-init.js", "assets/smart-anchor.js", "assets/pagetoc/sidebar.js", "assets/mdbook-quiz/embed.js"]
additional-css = ["assets/pagetoc/pagetoc_style.css", "assets/css/mdbook-admonish.css", "assets/css/open_on_gh.css", "assets/mdbook-quiz/embed.css"]
mathjax-support = true
# mdbook-open-on-gh preprocessor
git-branch = "main"
open-on-text = "Found a bug? [Edit this page on GitHub.]"


[output.html.playground]
editable = true
copy-js = true

[output.html.fold]
enable = false
level = 0

# Enables the `mdbook-mermaid` preprocessor
[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.puml]
command = "mdbook-puml"

# Enables the `mdbook-checklist` preprocessor
[preprocessor.checklist]
title = "待完善: "

#[preprocessor.toc]
#command = "mdbook-toc"
#renderer = ["html"]
#max-level = 4

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

# cargo install mdbook-backlinks
#[preprocessor.backlinks]

# cargo install mdbook-variables
[preprocessor.variables.variables]
motto = "保持批判，有所取舍，知行合一，方见真我"

#[preprocessor.quiz]

# cargo install mdbook-cmdrun
[preprocessor.cmdrun]

[preprocessor.kroki-preprocessor]

[preprocessor.fluent]
dir = "materials/fluent"

[preprocessor.presentation-preprocessor]

# Enables the `mdbook-admonish` preprocessor
[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "2.0.0" # do not edit: managed by `mdbook-admonish install`
