[config]
skip_core_tasks = true


# Precommit
[tasks.precommit-cargo]
script = "cargo fmt && cargo clippy"

[tasks.precommit-js]
script = "cd js && pnpm fmt && pnpm lint"

[tasks.precommit.run_task]
name = ["precommit-cargo", "precommit-js"]


# Watch
[tasks.watch-cargo]
script = "cargo watch -x 'install --path . --debug --offline'"
install_crate = { crate_name = "cargo-watch" }

[tasks.watch-js]
script = "cd js && pnpm build -w"

[tasks.watch.run_task]
name = ["watch-cargo", "watch-js"]
parallel = true